## can be used for specific test cases e.g. unit tests without interacting with DB
services:
#    App\Domain\Model\Order\IOrderRepository:
#        alias: App\Infrastructure\Persistence\Repository\InMemoryOrderRepository
